### ISSUE TITLE
CLI output vtk

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#275]
The command line interface should have an option to enable VTK file output

**Comment by lkeegan** [comment]
see also #312

**Comment by SoilRos** [comment]
With the latest release of dune-copasi, this should be pretty easy since the state is now responsible for writing the vtk files.

**Comment by lkeegan** [comment]
resolved by #511, as all simulation settings are now saved in the sbml model & the CLI reads & uses these options when simulating
