### ISSUE TITLE
add simple events

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#282]
As suggested by @fbergmann It would be nice to be able to add simple events to a simulation, for example:
- at time `t`, change the value of some parameter

This should be straightforward to implement within the GUI:
- simulate until time `t`
- save the model state
- change the model, recompile the reaction terms
- simulate the new model starting at `t` with the previous model state

Have to think about
- how to present to the user
  - maybe an advanced simulation dialog?
- how to load/save from sbml?

**Comment by fbergmann** [comment]
if you had the option, of just pausing ... and then basically use something like your initial condition tools to either uniformly set a value, or a function, or an image (with the current state at that point for the selected variable be displayed) that would be perfect.

**Comment by fbergmann** [comment]
In SBML these things would be considered discrete events. As in the form: at time 10, set concentration of x to xxx. Of course the trouble is that in SBML the trigger could be any arbitrary thing, even not time related. But it would be fine to implement a subset, and just do time based triggers for now.
