### ISSUE TITLE
save display options

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#351]
As suggested by @sahle it would be good to save the plot display options:

- can be added to sbml as annotations
- probably should be combined with #321

**Comment by sahle** [comment]
I don't know if this should be a separate issue, but I think it fits here: If I use the "maximum over all species" setting, it seems to consider also species that are disabled for the plotting. Not necessarily technically wrong, but to me it seems more intuitive if the scaling involves only the species that are actually displayed.
