### ISSUE TITLE
improve DUNE initial concentration import

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#401]
Initial species concentrations are imported into DUNE in two ways:

- GUI simulations: via the `GridFunction` class which provides a `Dune::PDELab::GridFunctionBase` object which returns the concentration at the pixel which corresponds to  a given `Element` and local position
- external simulations: from TIFF files that have a 16-bit integer for each pixel & a corresponding equation in the ini file that rescales them to give the concentration

In both cases, it may be that the point at which DUNE looks for the concentration lies exactly on the boundary between two pixels (this is actually often the case since this is where most of the vertices are). In general it doesn't matter which pixel is used, except when one pixel lies in a different compartment. In this case:

- the `GridFunction` class looks for a nearby pixel in the desired compartment & uses that instead
- the TIFF file returns zero for a pixel outside the desired compartment

Todo:

- the pixels outside the compartment should be filled with the concentration of the nearest pixel inside the compartment
  - this can be done using the spiral-out algo used to find the centre of compartments
  - might be worth using openCV to dilate the compartment to identify neighbouring pixels, rather than doing all external pixels (or looking at neighbours of the pixel contours of the compartment)
  - remove the `getNearestValidPixelConcentration` logic from the `GridFunction` class
- benefits
  - the TIFF import will no longer have spurious zeros in the initial concentrations
  - GridFunction and TIFF import methods will give consistent (at least up to 16-bit precision) results

**Comment by SoilRos** [comment]
I guess you already noticed that the TIFF utility `TIFFGrayscale` is converted to a function parsed by `muParser` and further converted into a `GridFunction` to be fed into the DUNE initial state. AFAIU, the problem you describe lies in `TIFFGrayscale` which maps pixels outside of its grid-domain to zero (with grid-domain, I mean the coordinate system encoded within the TIFF file, not the dune-grid nor the i,j indices used to map the data from the TIFF file) I thought zero would be a sensible default value, but it seems that is causing more problems than it should be. If you think it is more convenient, I wouldn't have any problem having other options for mapping values outside the grid-domain of the TIFF file (e.g.. throwing an error, finding nearest valid domain, extrapolate, etc.)

**Comment by lkeegan** [comment]
@SoilRos I think there are two (related) issues here. In both cases we start with a vertex lying on the boundary between two pixels, such that either of these two pixels in the TIFF could be used by `TIFFGrayscale`, depending on numerical rounding.

The two situations where this can be a problem:

1. The pixel might be in another compartment
    - This is what I describe above
    - This can be fixed on the GUI side by changing the TIFF files as described above

2. The pixel might be outside of the TIFF image
    - This is what you describe above

I generally agree with zero being a good default, but here the most convenient (from my point of view) way to deal with pixels that lie outside of the grid-domain would be to simply clamp the i,j indices to the nearest valid pixel in the TIFF - e.g. `i = std::clamp(i, 0, cols()-1)`(assuming `i` is a signed integer).

**Comment by SoilRos** [comment]
Alright, I see the problem. Thanks for the explanation! Then, you _really_ need the nearest pixel method in the TIFF input. That would solve the two things I guess. Still, I will implement the clamping thing on my side.

**Comment by lkeegan** [comment]
@SoilRos thanks, that would be great!
