### ISSUE TITLE
dune empty compartment membrane reaction

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#435]
It is not clear to me how to construct an ini file for a model like this one:

[single_compartment_membrane_reaction_dune.xml.txt](https://github.com/spatial-model-editor/spatial-model-editor/files/6089306/single_compartment_membrane_reaction_dune.xml.txt)

- the only reaction is on the membrane between the two outer compartments
- it results in a flux of the only non-constant species in the model into the inner of these compartments

![reac](https://user-images.githubusercontent.com/12845624/110091911-48d02180-7d99-11eb-840f-d7198cc1412f.png)

This species should flow into the compartment from the membrane:

![conc](https://user-images.githubusercontent.com/12845624/110091713-0b6b9400-7d99-11eb-9ab8-e3475a9449f4.png)

But how to represent this in dune-copasi?

- can't just have a single compartment & specify a boundary flux term from the outside
  - this would result in an influx from the inner hole boundary as well, which is not in the model
- can't have an empty outer compartment
  - do we need to add a dummy species to the empty compartment?

**Comment by SoilRos** [comment]
What I understand is that you want to set a boundary condition instead of an inter-compartment transmission condition. Is that correct?

**Comment by lkeegan** [comment]
@SoilRos yes, but the location where the boundary condition should apply in this model is only the outer boundary of the compartment (the purple-black line in the image). The compartment also has an inner boundary around a hole, where the default no-flux different boundary condition should apply.

The only way I see to do this currently is as an inter-compartment transmission, where the external compartment only exists to specify the boundary where the inter-compartment transmission condition applies, and I guess it has to have a dummy species in it since compartments with no species are not supported?

**Comment by SoilRos** [comment]
I see. Yes, currently there is only a no-flux condition on the boundary and your approach should work. In theory, the parser for flux in the intersections can handle space through conditionals, and thus a boundary condition that implements a similar feature should also do. But in practice, conditionals will be a killer for this kind of geometry. 
* I guess this could be improved by custom functions, but that won't happen while we use muParser to parse these fluxes. Not sure about other parsers.
* Having empty compartments is not supported right now, but it could indeed be a good solution! I could check it out after next week.
* Another form would be to attach a different form of boundaries according to the boundary info passed through GMSH.

**Comment by lkeegan** [comment]
> * Having empty compartments is not supported right now, but it could indeed be a good solution! I could check it out after next week.

If this would be possible to implement that would be great!
