### ISSUE TITLE
improve error messages when failing to load SBML model

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#449]
**Is your feature request related to a problem? Please describe.**
Currently, when loading an SBML file and something went wrong, the only error message visible is `failed to load <filename>`. This makes it hard to diagnose what could have gotten wrong. 

**Describe the solution you'd like**
Ideally there would be additional information about what is wrong with the model as to why it could not be loaded. Personally, i'd even be happy with a partial model being loaded in, allowing the user to fix issues that occurred along the way.

**Comment by lkeegan** [comment]
thanks Frank, would you mind sending me the SBML file?

there should be some more info logged to the terminal (but not yet in the GUI)

**Comment by fbergmann** [comment]
I've tried examples from: 

<https://sourceforge.net/p/sbml/code/HEAD/tree/trunk/specifications/sbml-level-3/version-1/spatial/specification/examples/>

and 

<https://github.com/fbergmann/spatial-sbml/tree/master/examples>

in order to find some that would work in more than one tool. It could be that some of the examples are in an old format. Though there also was a crash when loading the spec examples.

**Comment by lkeegan** [comment]
There are two kinds of possible problem when loading a model:
- libSBML gives an error on reading the file
  - #608 now displays the libSBML error message for the user to diagnose the issue
- we encounter something we don't support / understand
  - typically we silently ignore these things and continue loading the model
