### ISSUE TITLE
cannot import older spatial spec sbml models

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#454]
**Describe the bug**
SBML models using v0.84 of the spatial specification cannot be imported: get "failed to load file" error

**To Reproduce**
Import one of the models here:
https://github.com/fbergmann/spatial-sbml/tree/master/examples/v0.84

**Comment by lkeegan** [comment]
@fbergmann libSBML gives lots of errors on importing these files, I guess due to changes in the spatial spec - would it be ok with you if we focus on supporting the (eventual) v1 released spatial spec?

**Comment by fbergmann** [comment]
absolutely, no need at all to load the old files
