### ISSUE TITLE
reactions missing on imported model

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#458]
**Describe the bug**
Importing this analytic geometry model works:
https://github.com/sbmlteam/sbml-spatial-models/blob/master/Analytic%20models/fish_300x300.xml
but the reactions are missing

Likely the cause is that the reaction math contains piecewise functions, which we don't support for reaction terms.

Currently also no plan to support this, as we would need to translate them to infix that muparser can parse for dune to evaluate them, which looks hard to do reliably.

We should at least display a warning to the user that the reactions are being ignored though... (and check that they don't cause any issues if the model is modified and simulated)

**Comment by fbergmann** [comment]
Didn't see this one before! if it is not something that could be exchanged reliably, then of course its absolutely fine to leave out. I can rewrite the example different reactions in that case. In general though, i could see piecewise expressions being used for non homogeneous initializations. So it would be nice if SME could support it, and then pass it on as sampledfield to the dune solver or something like that.

**Comment by fbergmann** [comment]
Ultimately I think it would be nice to cover the full instruction set of equations that we can generate from COPASI. That way we could be sure to be able to 'just use' those models in SME. But it is a nice-to-have. So definitely not a priority.

**Comment by lkeegan** [comment]
- initial cause of missing reactions was them not having a compartment, fixed in #522 
- support for `piecewise` function (and all other L3 sbml math) in reactions added in #572
- model is now loaded correctly and can be simulated with pixel
- dune does not yet support `piecewise`, but it will once it switches from muparser to symengine, without any further changes required here
