### ISSUE TITLE
import copasi files directly

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#493]
**Describe the solution you'd like**
currently, COPASI files have first to be exported to SBML before they can get into SME. Maybe an option to import COPASI files would be nice to have. I was thinking here, of making that available if `CopasiSE` is in the path, and just invoking it to export the SBML file directly (to SBML L3V1). The command line would be: 

`CopasiSE -e out_sbmlfile.xml --SBMLSchema L3V1 copasifile.cps`

**Comment by lkeegan** [comment]
@fbergmann this would be good to have!

I could also imagine adding libcopasise to the bundled static libs, then we could import cps files without requiring copasiSE to be installed and in the path - does that sound like a reasonable way to do this to you?

Although I guess most people who want to import cps files would also have copasi installed, so maybe bundling the lib is overkill...

**Comment by fbergmann** [comment]
Yeah, i was thinking it would add too many more libraries to add libCopasiSE, so it would be easier to just use the CopasiSE one. But either one works

**Comment by lkeegan** [comment]
@fbergmann this should work now with the [latest](https://github.com/spatial-model-editor/spatial-model-editor/releases/tag/latest) binaries

**Comment by lkeegan** [comment]
resolved by #525
