### ISSUE TITLE
display reaction scheme on selected reaction

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#495]
**Describe the solution you'd like**
currently, while stoichiometries are displayed for the selected reaction, it would also nice to see the reaction scheme displayed as string (maybe next to the name). 

So rather than just seeing -1 A, 1 B ... we would also see "A -> B" displayed on top. 

Incidentally, area you only allowing integer stoichiometries? (as i noticed the spin box being used)

**Comment by lkeegan** [comment]
thanks @fbergmann, displaying the reaction scheme is a good idea & nice catch on the integer stoichiometries!
