### ISSUE TITLE
SME specific features in custom annotation

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#496]
**Describe the solution you'd like**
I was wondering if it would be useful to store SME specific features in the SBML export as custom annotation (such as the colors selected for species, the simulation ranges ... perhaps the selected simulator?

**Comment by lkeegan** [comment]
The species colours are stored as an annotation, e..g.:
```
<species>
        ...
        <annotation>
          <spatialModelEditor:colour xmlns:spatialModelEditor="https://github.com/lkeegan/spatial-model-editor" spatialModelEditor:colour="4294945280"/>
        </annotation>
        ...
</species>
```

I wasn't sure if simulation parameters belonged in the sbml model - I was thinking of saving them along with the simulation results in the sme file (see #482), but we could also add them to the sbml model if it would make sense to have them there.

**Comment by fbergmann** [comment]
I didn't see that! The best practices for SBML suggest, that it would be best to create just one custom annotation on the model element, containing the annotations for all elements customized. That way they are easier preserved by other tools. But its fine to me if you want to leave them on the species itself. I could imagine that it would be nice to preserve additional settings, such as whether to scale individually or globally and such would be nice to have as well. It is definitely not something urgent.

**Comment by lkeegan** [comment]
We currently also add annotations to a few other elements, e.g. the scaling you mention is stored on the model element:

```
  <model>
    <annotation>
      <spatialModelEditor:displayOptions xmlns:spatialModelEditor="https://github.com/lkeegan/spatial-model-editor" spatialModelEditor:showMinMax="1" spatialModelEditor:normaliseOverAllTimepoints="1" spatialModelEditor:normaliseOverAllSpecies="1" spatialModelEditor:showSpecies="1 0 0 1 1"/>
    </annotation>
 ...
```

Looking at copasi and the examples in the sbml spec, both seem to add annotations to the elements they are customizing.

But you are saying it would be better to put everything in one model annotation, so something like:
```
  <model>
    <annotation>
      <spatialModelEditor xmlns="https://github.com/lkeegan/spatial-model-editor">
        <displayOptions ... />
        <speciesColor ... />
        ...
      </spatialModelEditor>
    </annotation>
 ...
```

Is that right?

**Comment by fbergmann** [comment]
it is perfectly alright to add annotations wherever you would like them to be. So as far as i can tell, you are already doing all the custom annotations. So this issue can be closed. Sorry for the noise.

**Comment by lkeegan** [comment]
@fbergmann thanks - I've just added the simulation settings (#511) which were missing, I think now all sme settings are stored in the sbml file as custom annotations.
