### ISSUE TITLE
copy computed value to clipboard / make text selectable

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#498]
**Describe the solution you'd like**
Since it came up that a workflow might contain in reading of computed numbers from a label (computed area / length), it might be nice to have those numbers selectable, or just copy them to clipboard when clicking on them.

**Comment by lkeegan** [comment]
I agree, just checked and the numbers are already selectable (via mouse click&drag or double-click) on macos/linux/windows
