### ISSUE TITLE
Zoom functionality for compartment selection

### ISSUE THREAD

**Issue by BaronvonderHeyden** [spatial-model-editor/spatial-model-editor#516]
"Select geometry compartment..." can be very difficult if the compartment consists of relatively few pixels in a relatively large picture.

It would be helpful if it was possible to zoom in on the picture, so that selecting is easier.

**Comment by lkeegan** [comment]
@BaronvonderHeyden this should now be avilable in [latest](https://github.com/spatial-model-editor/spatial-model-editor/releases/download/latest/spatial-model-editor.exe) (version `1.0.9+9f3eff9`)

**Comment by BaronvonderHeyden** [comment]
thanks!
