### ISSUE TITLE
Support for GUI/CLI on MacOS 10.14 Mojave

### ISSUE THREAD

**Issue by SoilRos** [spatial-model-editor/spatial-model-editor#669]
**Is your feature request related to a problem? Please describe.**
The binary produced by the CI is not usable under MacOS 10.14 Mojave. What is needed for this to be supported? is it worth the effort?

**Comment by lkeegan** [comment]
Thanks for the report - I can reproduce the problem that the binaries are now requiring macos 10.15 or higher.
In principle 10.14 should be supported, so something is wrong somewhere - I'll look into this.

**Comment by lkeegan** [comment]
@SoilRos this should now be fixed in the latest pre-release binary:

https://github.com/spatial-model-editor/spatial-model-editor/releases/download/latest/spatial-model-editor.dmg

**Comment by SoilRos** [comment]
Great! Thank you :)
