### ISSUE TITLE
image sample field values

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#710]
**Describe the bug**
Full disclosure, this is not a bug, more of a question. Perhaps even a libSBML bug, but i would still like to know. The numbers in the geometryImage Sample field are huge (so huge in fact, that other tools fail to read the model), like: 

```
 <spatial:listOfSampledFields>
        <spatial:sampledField spatial:id="geometryImage" 
                   spatial:dataType="uint32" spatial:numSamples1="100" 
                   spatial:numSamples2="100" spatial:interpolationType="nearestNeighbor" 
                    spatial:compression="uncompressed" spatial:samplesLength="10000">

                          4278190592 4278190592 4278190592 4278190592 4278190592
                           4278190592 4278190592 4278190592 4278190592 4278190592 
                           4278190592 4278190592  .....
```

i was just wondering how this comes about. If i was encoding a model, i would probably just choose a `uint8` field, since it is unlikely to have more than 255 levels for the sample field. It just would be nice to know.

**To Reproduce**
create new model, add any image as geometry, save as sbml

**Expected behavior**
its not wrong, but it would be nice to know where the numbers come from. 

**Screenshots**

**Comment by lkeegan** [comment]
@fbergmann the number is just the colour of that pixel in the orginal compartment geometry image (alpha, red, green, blue components as a unit32, i.e. 0xAARRGGBB)

I'm using the string overload of `getSamples` with libSBML - but using the (signed) int overload of `getSamples` would likely give negative values which I guess could cause problems for other tools?

If so, we could change to using `0`, `1`, `2` to index each colour as you suggest, and maybe put the corresponding argb colour values for each index as custom annotations instead - would that be better do you think?

**Comment by fbergmann** [comment]
I think going to indexed colors would indeed be a good idea. And preserving the information as annotation seems right to me. 

Thank you

**Comment by lkeegan** [comment]
@petr for reference here are some relevant parts in the code for making this change:

## Import
Here we set a color from a pre-defined array of colors `common::indexedColours()` based on the index of each `sampledVolume` aka compartment:
https://github.com/spatial-model-editor/spatial-model-editor/blob/fc5fa70d0e484c66e8c1d31de0e9d391717c40ae/core/model/src/geometry_sampled_field.cpp#L186
This should be changed to use the array of colors stored as an annotation in the model (if it exists)

## Export
Here we export each pixel as a uint32:
https://github.com/spatial-model-editor/spatial-model-editor/blob/fc5fa70d0e484c66e8c1d31de0e9d391717c40ae/core/model/src/geometry_sampled_field.cpp#L281
As the image is already an indexed QImage this should just be a matter of changing to exporting the index of the color: `compartmentImage.pixelIndex`

## Annotation
Add e.g. a `std::vector<QRgb> compartmentColours` member to:
https://github.com/spatial-model-editor/spatial-model-editor/blob/fc5fa70d0e484c66e8c1d31de0e9d391717c40ae/core/model/include/sme/model_settings.hpp#L70-L89

Need to bump the cereal class version for this.

## Tests
We should add tests (e.g. to `common/src/serialization_t.cpp`) that
- import a model saved using the current (1.3.1) format
  - check the colors are correctly imported
  - export it in the new format
  - re-import it, check colors are correct
- Import a model in the new (1.3.x) format
  - with
    - valid color annotations
    - invalid color annotations
    - missing annotations
  - and for each export, re-import & check colors are correct
Would also be good to add some tests in `model/src/geometry_sampled_field_t.cpp` (this file is currently missing a `_t.cpp` test file)

## Sample models
The sample models (https://github.com/spatial-model-editor/spatial-model-editor/tree/main/core/resources/models) should then each be re-saved in the new format. (These files are included in the compiled GUI)

**Comment by piterand** [comment]
@lkeegan I have added the first working prototype with the new import and export format.

**Comment by lkeegan** [comment]
@piterand Great! Could you create a branch here on this repo with this & open a PR so that the CI runs?
