### ISSUE TITLE
support piecewise in math

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#814]
**Is your feature request related to a problem? Please describe.**
If you try to load the following test model: 

<https://raw.githubusercontent.com/sbmlteam/sbml-spatial-models/master/Analytic%20models/fish_300x300.xml>

and try to simulate it, it complains about an invalid piecewise expression being used in math. 

**Describe the solution you'd like**
supporting piecewise would be hopefully as simple as implementing an n-ary function. While there might be some discontinuities, in the past these just worked fine for the models that used them.

**Comment by lkeegan** [comment]
Hi Frank,

Thanks for the bug report - currently piecewise functions are not supported by DUNE.

The Pixel simulator does support all sbml L3 math, so the model can be simulated by going to
`Tools -> Set simulation type -> Pixel`

The ideal long term solution would be for DUNE to change symbolic math parser from muparser to symengine (this is the library that Pixel uses for symbolic math and to which I contributed an sbml parser).

In the meantime maybe a more helpful error message for the user that suggests trying the Pixel simulator in this situation would be an improvement?

**Comment by fbergmann** [comment]
indeeed, seeing the hint to choose the pixel engine would be all i need. Thank you
