### ISSUE TITLE
Isosurface Extraction or Voxel to Mesh Conversion Algorithms

### ISSUE THREAD

**Issue by piterand** [spatial-model-editor/spatial-model-editor#825]
# The Primal/Dual Classification
The different approaches are listed at [https://swiftcoder.wordpress.com/planets/isosurface-extraction/](https://swiftcoder.wordpress.com/planets/isosurface-extraction/).

## Marching Cubes
1. Marching Cubes Tutorial
https://www.boristhebrave.com/2018/04/15/marching-cubes-tutorial/
https://www.boristhebrave.com/2018/04/15/marching-cubes-3d-tutorial/
https://www.boristhebrave.com/2022/01/03/resolving-ambiguities-in-marching-squares/
https://www.boristhebrave.com/2021/12/29/2d-marching-cubes-with-multiple-colors/
2. https://medium.com/zeg-ai/voxel-to-mesh-conversion-marching-cube-algorithm-43dbb0801359
3. https://0fps.net/2012/07/12/smooth-voxel-terrain-part-2/
4. https://www.sciencedirect.com/science/article/pii/S0965997818303053
5. http://paulbourke.net/miscellaneous/interpolation/
Example of 2d marching cubes
![Example of 2d marching cubes](https://miro.medium.com/max/1400/0*QPGCx_P_3ZvlMX5S.)

## Marching tetrahedra
More accurate, but a more time-consuming algorithm.
1. https://0fps.net/2012/07/12/smooth-voxel-terrain-part-2/
2. http://paulbourke.net/geometry/polygonise/
![Example of Marching tetrahedra](http://paulbourke.net/geometry/polygonise/polytetra2.gif)

## Dual Contouring
- Surface Nets
- Naive Surface Nets
- Dual Contouring
![Example of Dual Contouring](https://user-images.githubusercontent.com/8105097/188676454-f3995958-547d-4d07-a2ec-0834ace922d0.png)

1. https://0fps.net/2012/07/12/smooth-voxel-terrain-part-2/
2. http://www.boristhebrave.com/2018/04/15/dual-contouring-tutorial/

**Comment by piterand** [comment]
# Examples of existing libraries for 
1. Marching Cubes: 

- https://github.com/pmneila/PyMCubes PyMCubes is an implementation of the marching cubes algorithm to extract iso-surfaces from volumetric data.
- https://github.com/JustusThies/PyMarchingCubes PyMarchingCubesявляется ответвлением от PyMCubes, с другой реализацией фактической маршевой функции
- https://github.com/BorisTheBrave/mc-dc library covers how to implement 2d / 3d Marching Cubes and Dual Contouring.
- https://github.com/Magnus2/MeshReconstruction This is a small library that can reconstruct a triangle mesh from a signed distance function using the Marching Cubes algorithm and export it to a file in the obj format.
- https://github.com/swiftcoder/isosurface Isosurface extraction algorithms implemented in Rust.
- https://github.com/smistad/GPU-Marching-Cubes  A GPU implementation of the Marching Cubes algorithm for extracting surfaces from volumes using OpenCL and OpenGL. But this software has been moved into the [FAST framework](https://github.com/smistad/FAST/) where it is further developed and maintained.
- https://github.com/seung-lab/zmesh Vacancy: A Voxel Carving implementation in C++.
- https://github.com/aparis69/MarchingCubeCpp C++ implementation

2. Dual Marching cubes: 
- https://github.com/planaria/dmc (https://www.cs.rice.edu/~jwarren/papers/dmc.pdf)
- https://github.com/andygeers/DualMarchingCuboids Because the author is a bear of little brain, the solution needs to be easily understood and implemented without lots of complicated maths (or third party maths libraries which are almost as complicated as the maths itself)
- 
4. Marching Tetrahedra: 
- https://github.com/Calvin-L/MarchingTetrahedrons
- https://github.com/andresbejarano/MarchingTetrahedra Require VTK library
- https://github.com/dborah123/marching-tetrahedra This project was built in flux.

3. Combine 
- https://github.com/JuliaGeometry/Meshing.jl This package provides a comprehensive suite of meshing (isosurface extraction) algorithms for use on distance fields and other structured datasets. Algorithms included: Marching Tetrahedra, Marching Cubes, Naive Surface Nets. Written on Julia.
- https://github.com/voxelbased/core Voxel-based is a collection of voxel algorithm implementations for the Unity Engine. Algorithms included: Boxel, Marching Cubes, Marching Tetrahedra, Naive Surface Nets, Dual Contouring of Hermite Data, Cubical Marching Squares. Written on С#.

**Comment by lkeegan** [comment]
Thanks @piterand! Adding a link to similar functionality in CGAL (which we already use for the 2d meshing):
- https://doc.cgal.org/latest/Manual/tuto_reconstruction.html
- https://doc.cgal.org/latest/Manual/packages.html#PartReconstruction

**Comment by lkeegan** [comment]
Turns out CGAL has functionality to directly go from a segmented 3d image to a 3d mesh, so the initial plan is to just use this: https://doc.cgal.org/latest/Mesh_3/index.html#Mesh_3DomainsFromSegmented3DImages

**Comment by lkeegan** [comment]
resolved by #937
