### ISSUE TITLE
Support for COMBINE Archives?

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#828]
**Is your feature request related to a problem? Please describe.**
Frequently we encounter models encoded as combine archives. Currently, i dont think those can be directly loaded into SME. I wonder if it would make sense to just open them up automatically using libCombine. 

**Describe the solution you'd like**
Add [libcombine](https://github.com/sbmlteam/libcombine) to the dependencies, and if an archive is loaded into SME, use it to import an SBML model.

**Comment by lkeegan** [comment]
@fbergmann Thanks, sounds like a good idea to me. Could you point me to a small combine archive I should use for testing?

**Comment by fbergmann** [comment]
A very basic example would be <https://share.getcloudapp.com/geuyOgkr> where i just wrapped one of SME's examples into an archive. We expect a large number of VCell files in a similar format.

**Comment by lkeegan** [comment]
@fbergmann the latest version (1.3.2) should now support reading combine archives - let me know if there's anything missing or not working

**Comment by fbergmann** [comment]
thanks, that is working great so far. I'll go though all vcell models once i'm back and file issues if some come up. The files i've tested for now work nicely.
