### ISSUE TITLE
why uint32?

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#830]
I've spend the evening trying to get some SME models into vcell, as it turns out the sampled fields exported from SME all use unit32, even though they are nicely segmented and would only need uint8. I wonder where this comes from. This might be a libSBML issue. 

Apart from making it easier for vcell to import the models, it would also make the files much smaller, if instead of `4278719745` we'd export `1`. It would be nice if we'd sort this.

**Comment by lkeegan** [comment]
@fbergmann see #710 for the original reason for uint32 - but as discussed in that issue happy to change to indexed colors instead and in fact I started looking at this together with @piterand yesterday, will keep you updated on our progress!

**Comment by fbergmann** [comment]
thank you! i should have added this to the  other  bug
