### ISSUE TITLE
wrong display of simulation results. 

### ISSUE THREAD

**Issue by fbergmann** [spatial-model-editor/spatial-model-editor#852]
**Describe the bug**
the attached model has species with uniform initial concentrations 'RLP44' = 1,  'aRLP44' = 0. When simulating the model in the SME gui, using either DUNE or pixel, the displayed result shows that an initial concentration of 1 is used for 'aRLP44' and 0 for 'RLP44', which is not expected. 

Oddly, when performing the same simulation using python, this is not the case. 

**To Reproduce**

* [download the model](https://p194.p3.n0.cdn.getcloudapp.com/items/7Kuzekko/5e8cbecc-5d96-4751-96d4-24e95eff5ff1.sme?v=dcf398f31ad7928ff9ede2d72f36c3aa)
* Load the file into SME, 
* select simulation tab, 
* hit simulate. 
* You'll notice the unexpected initial concentrations displayed. 

**Expected behavior**
What you expected to happen.

**Screenshots**

Python session: 
![Screenshot of python session](https://p194.p3.n0.cdn.getcloudapp.com/items/yAuJ7QyR/60c928bb-c05e-4e49-90ab-c26ece1ea551.jpeg?v=52ee5333c72c7acf1d02416c72506094)

SME display:
![SME display](https://p194.p3.n0.cdn.getcloudapp.com/items/nOuKdbXl/f5ae5140-c1a1-4822-a67b-60945091ceb8.jpeg?v=0fd1c7d413455b63abf168d14d52bd7e)

**Comment by lkeegan** [comment]
@fbergmann thanks for the bug report, I'll look into it.

I can reproduce the issue as described when using DUNE, but if I use Pixel the initial concentrations are correct (if this is also the case for you it might explain why the python simulation works, as by default it uses Pixel):

https://user-images.githubusercontent.com/12845624/220632184-aea13761-b7e0-470b-9d17-31347a0bbc70.mp4

**Comment by fbergmann** [comment]
I've tried here on my machine at home, and indeed here it works with the pixel engine as well. It was a user error, I first simulated with DUNE, then changed to pixel, and clicked simulate again, without pressing reset. Maybe the reset should happen automatically when changing engines?

Anyway thanks for fixing this so fast.

**Comment by lkeegan** [comment]
@fbergmann great, thanks - the DUNE initial concentrations should now be correct in the latest pre-release:

https://github.com/spatial-model-editor/spatial-model-editor/releases/download/latest/spatial-model-editor.exe

The reset should actually be optional, as it is supported for the user to simulate with one simulator, then change simulator and continue the same simulation.

I also need to fix an unrelated macos build issue, then I'll make a new release with this bug fix.
