### ISSUE TITLE
Parameter Order affects simulation result in commutative function

### ISSUE THREAD

**Issue by formersbach** [spatial-model-editor/spatial-model-editor#857]
**Describe the bug**
Using functions to define reaction kinetics, the order of parameters changes the simulation results while using a commutative rate law. Might be potentially connected to #855.

**To Reproduce**
- [Download models.](https://heibox.uni-heidelberg.de/d/8c8798a4665d4af290c4/)
- Both models are identical except for the order in which the parameters are supplied to the function
- Run simulation using PIXEL solver
- Notice slightly different output

**Expected behavior**
Both models should behave identically, since the order of parameters should not matter for the particular functions used.

**Screenshots**
Parameter order A:
![Model1](https://user-images.githubusercontent.com/49982367/222415862-3ac363cc-a094-46a5-aa17-3d68a96099e6.png)
)

Parameter order B:
![Model8](https://user-images.githubusercontent.com/49982367/222415901-f1a29e1d-b253-4e90-9333-743be74a0419.png)

**Comment by lkeegan** [comment]
@formersbach thanks! It turns out both this and your other bug report have the same root cause (https://github.com/spatial-model-editor/spatial-model-editor/issues/856#issuecomment-1451919941).
I'll try to release a new version with this bug fixed tomorrow.

**Comment by lkeegan** [comment]
@formersbach these issues should now be fixed in the latest (1.3.5) release - thanks for the bug reports and please let me know if you run into any other issues.

**Comment by formersbach** [comment]
@lkeegan Thanks for the quick work, will do!
