### ISSUE TITLE
Error while importing TIFF

### ISSUE THREAD

**Issue by purusharths** [spatial-model-editor/spatial-model-editor#862]
**Describe the bug**
Ambiguous error while importing custom tiff files (https://imgur.com/a/lzsmsYj)     

![Screenshot_20230514_172744](https://github.com/spatial-model-editor/spatial-model-editor/assets/5101224/2e57c024-3af7-44a9-8761-d18ff3a4fb82)

I could trace a bit of the error by opening the editor via terminal:
```
TIFFReadDirectory: Warning, Unknown field with tag 50784 (0xc660) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 50790 (0xc666) encountered.
```
However, even this was only there for the [black and green image](https://i.imgur.com/S1yXmMS.png) and not for the other one

PS: imgur converts images to .png, the ones I tried to import were .tiff itself.

**Expected behavior**
Successful geometry import from the image file.

**Comment by lkeegan** [comment]
Thanks for the bug report, I could import the png version of the images without issues - could you share the original tiff image files that produced the error?

**Comment by purusharths** [comment]
Interesting. I thought only .tif files could be imported. I was able to load the png as well, however,  

The corrosponding tiff files are uploaded here: https://heibox.uni-heidelberg.de/d/08a30f226ed349c79aa3/

**Comment by purusharths** [comment]
@lkeegan ah alright. That explains it :) Thanks a lot!

Is there an option to add material properties within the editor itself? I checked a doc but didn't find anything - I can open a feature request if required. 

Thanks again for the explanation :+1:

**Comment by lkeegan** [comment]
@purusharths you're welcome! I'm not sure what you mean by "material properties" - you can set the diffusion constant for each species within a compartment, but otherwise the compartment just defines the geometry, so I guess the answer is probably no, but feature requests are always welcome..
