### ISSUE TITLE
cgal mesh -> dune grid / dune docs

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#881]
@nashmit (putting this here and not in slack so it doesn't disappear)
So the mesh in dune is a bit complicated:
- https://gitlab.dune-project.org/copasi/dune-copasi
  - dune-copasi is the FEM solver we use that is built on top of DUNE
  - it can read a gmsh format mesh from a file: https://gitlab.dune-project.org/copasi/dune-copasi/-/blob/master/dune/copasi/grid/multidomain_gmsh_reader.hh
    - so one thing our Mesh can do is export to a gmsh file
  - but we can also directly create the dune grid to avoid going via a gmsh file
    - https://github.com/spatial-model-editor/spatial-model-editor/blob/main/core/simulate/src/dunegrid.hpp
- dune docs:
  - https://www.dune-project.org/doxygen/2.7.1/modules.html
  - see the `dune-geometry` and `dune-grid modules`
  - also in particular https://www.dune-project.org/doxygen/2.7.1/group__GeometryReferenceElements.html
  - (I mostly ended up looking through the code rather than the docs)
- Once you have a cgal mesh where you can iterate over vertices and tetrahedra, and know which compartment each tetrahedron belongs to:
  - we can look together at how to modify the existing code in sme that generates the 2d dune grid from our 2d mesh
  - it should be fairly similar with a few changes, e.g.:
    - Dune::GeometryTypes::triangle -> Dune::GeometryTypes::tetrahedron
  - we can also have a meeting with Santiago (the phd student who wrote dune-copasi) if we get stuck

**Comment by SoilRos** [comment]
I don't really understand from the description what you are trying to do, but maybe this is useful: a dune-grid wrapper for CGAL triangulation https://www.dune-project.org/modules/dune-mmesh/

**Comment by lkeegan** [comment]
resolved by #937
