### ISSUE TITLE
Use UMFPack solver in dune-copasi

### ISSUE THREAD

**Issue by lkeegan** [spatial-model-editor/spatial-model-editor#910]
For better dune-copasi performance we should:

- add suitesparse/metis/lapack/blas to bundled static libs
  - see https://github.com/spatial-model-editor/sme_deps_common/issues/28
- use `UMFPack` linear solver in ini file instead of `CG`

**Comment by SoilRos** [comment]
`UMFPack` is a good default, specially for testing small cases. But as matrices get bigger (e.g. N~1e6), iterative solvers start to pay off. For better performance in the assembly part, use the multi-threaded branches of dune-copasi and dune-pdelab. I will try to incorporate your clean up there too.

**Comment by lkeegan** [comment]
I'll stick with the master dune-copasi branch for now until everything is working, then try using the multi-threaded branches in a separate PR.

I guess the choice of solver should also be added to the dune-copasi options in the GUI (currently it is just hard-coded to `CG`):

https://spatial-model-editor.readthedocs.io/en/stable/reference/dune.html

**Comment by lkeegan** [comment]
this was resolved by #955 - user can now choose the solver in the GUI, with `restartedGMRes` as the default
