### ISSUE TITLE
Wrong default linear solver for dune solver

### ISSUE THREAD

**Issue by SoilRos** [spatial-model-editor/spatial-model-editor#958]
**Describe the bug**
The automatic linear solver by the editor is `CG`. This linear solver should be used when the system is symmetric positive definite, and this is **not** the case for our non-linear models.

**To Reproduce**
Open any non-linear example (e.g., circadian clock) and export the dune ini file.

**Expected behavior**
A solver that is suited for the task when the problem is non-linear. For example, `RestartedGMRes`, `BiCGSTAB`, or `UMFPack`.

_edit_: added "**not**" to the main argument.

**Comment by lkeegan** [comment]
Thanks - I didn't realise this! Would you recommend using RestartedGMRes or BiCGSTAB as the default?
(UMFPack is not yet possible as a default due to window/linux issues with the blas/lapack dependencies https://github.com/spatial-model-editor/sme_deps_common/issues/28)
